// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// import 'firebase_options.dart';
// ...
// Firebase.initializeApp(
//   options: DefaultFirebaseOptions.currentPlatform,
// );
// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJRGDaV4640y2rgsm6GW-wG5o6i4G0f_U',
    appId: '1:449655289689:web:cf1d66723ad8edefe93e48',
    messagingSenderId: '449655289689',
    projectId: 'ticket-scanner-7a283',
    authDomain: 'ticket-scanner-7a283.firebaseapp.com',
    storageBucket: 'ticket-scanner-7a283.appspot.com',
    measurementId: 'G-9E89BY4RVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8Q_RdxO_53GZov11tL-9kzPsIl6hh4Dk',
    appId: '1:449655289689:android:c9a605cb0ed41e34e93e48',
    messagingSenderId: '449655289689',
    projectId: 'ticket-scanner-7a283',
    storageBucket: 'ticket-scanner-7a283.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3GM6gdhJ8QY-YvFWH2jNjQhl3_p3481A',
    appId: '1:449655289689:ios:52d4c11dfa8fb0ede93e48',
    messagingSenderId: '449655289689',
    projectId: 'ticket-scanner-7a283',
    storageBucket: 'ticket-scanner-7a283.appspot.com',
    iosClientId: '449655289689-gns2rctah7vfci20e55qaaaae5rr5mc3.apps.googleusercontent.com',
    iosBundleId: 'com.example.ieeeTicketScanner',
  );
}
