// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcTCFTHkF29s8AjycJCtzJ3XeAO05t0Hs',
    appId: '1:1093192662099:web:cbfbd40a688d18f28bdaa6',
    messagingSenderId: '1093192662099',
    projectId: 'ticket-scanner-163c1',
    authDomain: 'ticket-scanner-163c1.firebaseapp.com',
    storageBucket: 'ticket-scanner-163c1.appspot.com',
    measurementId: 'G-PD3KQK8T0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEAXBXxq_pjcS_WOFLYrQX6E8BjIYvBIM',
    appId: '1:1093192662099:android:e8a8e39ec06180af8bdaa6',
    messagingSenderId: '1093192662099',
    projectId: 'ticket-scanner-163c1',
    storageBucket: 'ticket-scanner-163c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFEdcZzTVL2U02Cb7-qaRV9gI79Hojmsk',
    appId: '1:1093192662099:ios:390ad5abda0571b68bdaa6',
    messagingSenderId: '1093192662099',
    projectId: 'ticket-scanner-163c1',
    storageBucket: 'ticket-scanner-163c1.appspot.com',
    iosClientId: '1093192662099-4tu0e4d3dttkns6cr578h6dplnhbm7e1.apps.googleusercontent.com',
    iosBundleId: 'com.example.ieeeTicketScanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFEdcZzTVL2U02Cb7-qaRV9gI79Hojmsk',
    appId: '1:1093192662099:ios:390ad5abda0571b68bdaa6',
    messagingSenderId: '1093192662099',
    projectId: 'ticket-scanner-163c1',
    storageBucket: 'ticket-scanner-163c1.appspot.com',
    iosClientId: '1093192662099-4tu0e4d3dttkns6cr578h6dplnhbm7e1.apps.googleusercontent.com',
    iosBundleId: 'com.example.ieeeTicketScanner',
  );
}
